### ISSUE TITLE
Error - Expo Emulator (Android)

### ISSUE THREAD

**Issue by stephyswe** [creativetimofficial/argon-react-native#13] opened 2020-02-04 16:59 UTC
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [x] I'm reporting the issue to the correct repository (for multi-repository projects)

# Expected Behavior

With expo start and running "Start Android/Emulator" - starts app on emulated device

# Current Behavior

After starting Android/emulator app loads JS files up till 60% then returns error message
Opening on Android device
Unable to resolve "react-native-screens" from "node_modules\react-navigation-stack\lib\module\views\StackView\StackViewCard.js"
Failed building JavaScript bundle.

# Failure Information (for bugs)

I think it is a bug. Please help.

**Comment by palingheorghe** [comment] 2020-02-06 15:16
Hi @stephyswe ! Thank you for your interest in our products! 
This is because of the new `react-navigation` changes. Doing a `npm install` right now is installing the latest versions instead of the versions we've written in our package. 

Re-download the product and delete the "^" from package.json and then hit npm install. Things should work as intended now. 

Thanks,
Alin

**Comment by bozzmob** [comment] 2020-02-11 15:02
@palingheorghe Thanks for the reply. 
I tried what you suggested, I'm getting the following error-
```
Press ? to show a list of all available commands.
Logs for your project will appear below. Press Ctrl+C to exit.
Unable to resolve "./views/ThemeContext" from "node_modules/@react-navigation/core/lib/module/index.js"
Failed building JavaScript bundle.
Building JavaScript bundle [=================================================================================================== ] 99%
```

This is how my package.json looks like(not much changes except for  "react-navigation": "3.11.0")-
```
{
  "name": "argon-react-native",
  "version": "1.3.0",
  "description": "Argon React Native, based on Argon Design System. Coded by Creative Tim",
  "main": "node_modules/expo/AppEntry.js",
  "scripts": {
    "start": "expo start",
    "android": "expo start --android",
    "ios": "expo start --ios",
    "eject": "expo eject"
  },
  "repository": {
    "type": "git",
    "url": "git+https://github.com/creativetimofficial/argon-react-native.git"
  },
  "dependencies": {
    "expo": "^35.0.0",
    "expo-asset": "~7.0.0",
    "expo-font": "~7.0.0",
    "galio-framework": "^0.6.3",
    "prop-types": "^15.7.2",
    "react": "16.8.3",
    "react-native": "https://github.com/expo/react-native/archive/sdk-35.0.0.tar.gz",
    "react-native-gesture-handler": "~1.3.0",
    "react-native-modal-dropdown": "^0.6.2",
    "react-navigation": "3.11.0"
  },
```

**Comment by PA55ION** [comment] 2020-02-12 05:26
@stephyswe Did you solve the issue? I got the same error that you were getting. @palingheorghe  remove"^" from react-navigation? or react-navigation-stack?

**Comment by palingheorghe** [comment] 2020-02-12 16:55
Hi! @PA55ION I'm talkin about all packages so they won't get any updates. @stephyswe & @PA55ION : As I can see the error still thinks you got @react-navigation installed, you should clear the cache by removing `node_module`, `.expo` and `package-lock.json` and then reinstall all the packages and start the project by using the following command: `expo r -c` which should reset the cache and make the project work again as intended.

Thanks,
Alin

**Comment by bozzmob** [comment] 2020-02-13 07:27
@palingheorghe Thanks. Yes, you were right, I had to remove  `node_module`, `.expo` and `package-lock.json` and then everything worked as intended.

**Comment by palingheorghe** [comment] 2020-02-13 15:37
I'll close this issue based on the fact that this solution is working. Thank you everybody! ❤️

**Closed by palingheorghe** 2020-02-13 15:37 UTC

**Comment by triloconinja** [comment] 2020-02-21 10:14
Hi I'm still receiving  an error undefined is not an object (evaluating '_reacNavigation. ThemeColors.light')


>  "dependencies": {
    "expo": "^35.0.0",
    "expo-asset": "^7.0.0",
    "expo-font": "^7.0.0",
    "galio-framework": "^0.6.3",
    "prop-types": "^15.7.2",
    "react": "16.8.3",
    "react-native": "https://github.com/expo/react-native/archive/sdk-35.0.0.tar.gz",
    "react-native-gesture-handler": "~1.3.0",
    "react-native-modal-dropdown": "^0.7.0",
    "react-native-reanimated": "~1.2.0",
    "react-native-svg": "^9.9.5",
    "react-navigation": "3.9.0",
    "react-navigation-drawer": "^2.3.1",
    "react-navigation-stack": "^1.9.4",
    "react-navigation-tabs": "^2.5.6"
  },

**Comment by palingheorghe** [comment] 2020-02-21 12:29
Hi @triloconinja ! Could you please give us more information regarding your issue? I don't think it's related to this one so the best thing would be opening up a new issue with more information about your error. 

Thanks

**Comment by dhirenchotwani** [comment] 2020-02-27 07:32
Hi @palingheorghe What does the statement removing from cache means ? I downloaded the package , extracted it and what am i supposed to do now ? 
Thankyou so much for your help!

**Comment by dhirenchotwani** [comment] 2020-02-27 07:48
> @palingheorghe Thanks. Yes, you were right, I had to remove `node_module`, `.expo` and `package-lock.json` and then everything worked as intended.

How did you remove `node_module`, `.expo` and `package-lock.json` ? can you explain in a brief ?
